#theme: jekyll-theme-slate
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
title: trueLinQ
description: Jusr.Verified
logo: "//cdn.truelinq.com/_common/static/truelinq/linq-main-page-150.png"
aux_links:
  "Create Account":
    - "//app.truelinq.com/linq/"

# External navigation links
#nav_external_links:
#  - title: Just the Docs on GitHub
#    url: https://github.com/just-the-docs/just-the-docs