#theme: jekyll-theme-slate
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
title: trueLinQ
description: Simple.Secure.Sign.On
#baseurl: /docs
logo: "https://cdn.truelinq.com/_common/static/truelinq/linq-logo-150x50.png"
color_scheme: dark
aux_links:
  "Login":
    - "//app.truelinq.com/linq/"

# External navigation links
#nav_external_links:
#  - title: Just the Docs on GitHub
#    url: https://github.com/just-the-docs/just-the-docs
plugins:
  - jekyll-default-layout
gems:
  - jekyll-default-layout